
# NVIDIA (Turing+ with GSP firmware)
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Cursor
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
